# Generated by Django 4.0.3 on 2022-04-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_chamber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'documents'), (2, 'news')], verbose_name='Тип категорий'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type__in': [2]}, on_delete=django.db.models.deletion.PROTECT, to='accounts_chamber.category', verbose_name='Категория'),
        ),
    ]
