# Generated by Django 4.0.3 on 2022-04-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_chamber', '0002_alter_category_type_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Гос отчеты'), (2, 'План работ')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новости'), (2, 'Семинары'), (3, 'Выступления')], verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
