# Generated by Django 4.0.3 on 2022-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_chamber', '0003_alter_document_category_alter_posts_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='pagehtml',
            name='url',
        ),
        migrations.AddField(
            model_name='pagehtml',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Гос отчеты'), (2, 'План работ'), (3, 'Госслужба'), (4, 'Госзакупки'), (5, 'Информация о взаимоотношениях'), (6, 'Контрольные и экспертно-аналитические мероприятия'), (7, 'Порядок обжалования КСО'), (8, 'Информация о принятых по внесённым представлениям и предписаниям решениях и мерах'), (9, 'Информация о внесённых по итогам проведения контрольных и экспертно-аналитических мероприятий представлениях и предписаниях'), (10, 'Отчеты о исполнений бюджета'), (11, 'Документы по методологическому обеспечению '), (12, 'Нормативные документы'), (13, 'Нормативные акты'), (14, 'Коррупция'), (15, 'Комиссия (коррупций)'), (16, 'Антикоррупционная экспертиза'), (17, 'Сведения о доходах')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PDF'), (2, 'excel'), (3, 'word'), (4, 'другое')], verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='pagehtml',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
