# Generated by Django 4.0.3 on 2022-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_chamber', '0005_remove_employee_position_employee_main_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет в отображений'),
        ),
    ]
