# Generated by Django 4.0.3 on 2022-08-10 04:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_chamber', '0006_employee_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biography',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Гос отчеты'), (2, 'План работ'), (3, 'Госслужба'), (4, 'Госзакупки'), (5, 'Информация о взаимоотношениях'), (6, 'Контрольные и экспертно-аналитические мероприятия'), (7, 'Порядок обжалования КСО'), (8, 'Информация о принятых по внесённым представлениям и предписаниям решениях и мерах'), (9, 'Информация о внесённых по итогам проведения контрольных и экспертно-аналитических мероприятий представлениях и предписаниях'), (10, 'Отчеты о исполнений бюджета'), (11, 'Документы по методологическому обеспечению'), (12, 'Нормативные документы'), (13, 'Нормативные акты'), (14, 'Коррупция'), (15, 'Комиссия (коррупций)'), (16, 'Антикоррупционная экспертиза'), (17, 'Сведения о доходах')], verbose_name='Категория'),
        ),
    ]
